import { Link } from '@tanstack/react-router';
import { ArrowUpRight, Menu, X, Youtube, Instagram } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { ExternalLink } from '@/components/external-link';
export function Brand() { return <Link to="/" className="brand" aria-label="Markiplier home"><span className="brand-mark" aria-hidden="true">⌁</span>MARKIPLIER<span className="text-primary text-lg">.</span></Link>; }
export function SiteHeader() {
 const [open,setOpen]=useState(false);
 const navigation=<><Link to="/" activeOptions={{exact:true}} className="nav-link" onClick={()=>setOpen(false)}>HOME</Link><Link to="/archive" className="nav-link" onClick={()=>setOpen(false)}>ARCHIVE</Link><Link to="/community" className="nav-link" onClick={()=>setOpen(false)}>COMMUNITY</Link></>;
 return <header className="site-header"><div className="site-width grid h-full grid-cols-[minmax(0,1fr)_auto] items-center gap-4"><Brand/><div className="hidden items-center gap-11 md:flex"><nav aria-label="Main navigation" className="flex gap-8">{navigation}</nav><span className="h-5 border-l border-border"/><ExternalLink href="https://www.youtube.com/@markiplier" className="flex items-center gap-2 text-[11px] font-semibold">ON YOUTUBE <ArrowUpRight size={14} className="text-primary"/></ExternalLink></div><Button variant="ghost" size="icon" className="md:hidden" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div>{open&&<nav aria-label="Mobile navigation" className="grid gap-1 border-b border-border bg-stage px-5 pb-5 md:hidden">{navigation}</nav>}</header>;
}
export function SocialLinks({compact=false}:{compact?:boolean}) { return <div className="flex items-center gap-5"><ExternalLink aria-label="Markiplier on YouTube" href="https://www.youtube.com/@markiplier" className="text-muted-foreground transition-colors hover:text-primary"><Youtube size={compact?18:22}/></ExternalLink><ExternalLink aria-label="Markiplier on Instagram" href="https://www.instagram.com/markiplier/" className="text-muted-foreground transition-colors hover:text-primary"><Instagram size={compact?18:22}/></ExternalLink><ExternalLink aria-label="Markiplier on X" href="https://x.com/markiplier" className="text-muted-foreground transition-colors hover:text-primary"><span className="text-lg font-semibold">𝕏</span></ExternalLink></div>; }
export function SiteFooter() { return <footer className="footer"><div className="site-width flex flex-col gap-7 sm:flex-row sm:items-center sm:justify-between"><div><Brand/><p className="mt-3 text-[11px] text-muted-foreground">Made by fans. For fans. Not affiliated with Markiplier.</p></div><p className="text-[10px] text-muted-foreground">© 2026 MARKIPLIER FAN CLUB <span className="mx-2 text-primary">/</span> STAY WEIRD.</p><SocialLinks compact/></div></footer>; }
